import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// The Agent SDK is ESM-only and resolves a native CLI binary via its own
		// node_modules at runtime (dynamic require based on process.platform) —
		// bundling it breaks that resolution. Loaded via dynamic import() at
		// runtime instead, so it (and its own dependency, @anthropic-ai/sdk) must
		// stay external and ship as real node_modules next to main.js (see
		// copy-to-vault.mjs).
		"@anthropic-ai/claude-agent-sdk",
		"@anthropic-ai/sdk",
		...builtins,
		...builtins.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
